name: SegmentAppcues
attributes:
  ORGANIZATIONNAME: Appcues
options:
  defaultConfig: Release
  deploymentTarget:
    iOS: 13.0
  groupSortPosition: top
configs:
  Debug: debug
  Release: release
settings:
  base:
    CLANG_CXX_LANGUAGE_STANDARD: gnu++17
schemes:
  SegmentAppcues:
    analyze:
      config: Debug
    archive:
      config: Release
    build:
      targets:
        SegmentAppcues:
        - analyzing
        - testing
        - running
        - profiling
        - archiving
    profile:
      config: Release
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
      - SegmentAppcuesTests
targets:
  SegmentAppcues:
    type: framework
    platform: iOS
    settings:
      base:
        MARKETING_VERSION: 1.0.0-beta.3
        GENERATE_INFOPLIST_FILE: 'YES'
        PRODUCT_BUNDLE_IDENTIFIER: com.appcues.sdk
    sources:
    - path: Sources/SegmentAppcues
    dependencies:
      - package: Segment
      - package: AppcuesKit
    postbuildScripts:
    - name: SwiftLint
      script: 'xcrun --sdk macosx mint run swiftlint --path ./Sources'
  SegmentAppcuesTests:
    dependencies:
    - target: SegmentAppcues
    platform: iOS
    settings:
      base:
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: '1'
        GENERATE_INFOPLIST_FILE: 'YES'
        PRODUCT_BUNDLE_IDENTIFIER: com.appcues.SegmentAppcuesTests
    sources:
    - path: Tests/SegmentAppcuesTests
    type: bundle.unit-test
packages:
  Segment:
    github: segmentio/analytics-swift
    from: 1.0.0
  AppcuesKit:
    github: appcues/appcues-ios-sdk
    version: 1.0.0-beta.3
