name: Segment-Appcues
attributes:
  ORGANIZATIONNAME: Appcues
options:
  defaultConfig: Release
  deploymentTarget:
    iOS: 13.0
  groupSortPosition: top
configs:
  Debug: debug
  Release: release
settings:
  base:
    CLANG_CXX_LANGUAGE_STANDARD: gnu++17
schemes:
  Segment-Appcues:
    analyze:
      config: Debug
    archive:
      config: Release
    build:
      targets:
        Segment-Appcues:
        - analyzing
        - testing
        - running
        - profiling
        - archiving
    profile:
      config: Release
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
      - Segment-AppcuesTests
targets:
  Segment-Appcues:
    type: framework
    platform: iOS
    settings:
      base:
        MARKETING_VERSION: 0.1.0
        GENERATE_INFOPLIST_FILE: 'YES'
        PRODUCT_BUNDLE_IDENTIFIER: com.appcues.sdk
    sources:
    - path: Sources/Segment-Appcues
    dependencies:
      - package: Segment
      - package: AppcuesKit
    postbuildScripts:
    - name: SwiftLint
      script: 'xcrun --sdk macosx mint run swiftlint --path ./Sources'
  Segment-AppcuesTests:
    dependencies:
    - target: Segment-Appcues
    platform: iOS
    settings:
      base:
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: '1'
        GENERATE_INFOPLIST_FILE: 'YES'
        PRODUCT_BUNDLE_IDENTIFIER: com.appcues.Segment-AppcuesTests
    sources:
    - path: Tests/Segment-AppcuesTests
    type: bundle.unit-test
packages:
  Segment:
    github: segmentio/analytics-swift
    from: 1.0.0
  AppcuesKit:
    github: appcues/appcues-ios-sdk
    branch: main
